import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";

const space = Host_Grotesk({subsets: ['latin']})

export const metadata: Metadata = {
  title: "PasteBin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
